### ISSUE TITLE
Features v0

### ISSUE THREAD

**Issue by vinayak-mehta** [juneHQ/houseplant#2]
Supported commands:
- [ ] houseplant init
- [ ] houseplant generate add_events
- [ ] houseplant migrate:status
- [ ] houseplant migrate VERSION=2024xxx
- [ ] houseplant migrate:up VERSION=2024xxx
- [ ] houseplant migrate:down VERSION=2024xxx

Notes:
`ch/schema.yml`
```
  tables:
    - name: events
      metadata:
      sql:
```
`ch/migrations/2024xxx_events.yml`
```
  version: 2024xxx
  description: Create events table
  up:
    <<~SQL
    SQL
  down:
    <<~SQL
    SQL
```
